blueprint:
  name: "Modern Doorbell & Door Announcer v1.1"
  description: >
    Announce doorbell presses or door openings over Alexa. 
    Choose between a built-in sound or a custom voice message.
  domain: automation
  input:
    trigger_sensor:
      name: Doorbell or Door Sensor
      description: The binary sensor that triggers the announcement.
      selector:
        entity:
          domain: binary_sensor
    echo_devices:
      name: Alexa Devices
      description: Select all Alexa devices you want to announce on.
      selector:
        entity:
          domain: media_player
          multiple: true
    announcement_type:
      name: Announcement Type
      description: Choose if Alexa should play a sound or speak your custom text.
      default: "tts"
      selector:
        select:
          options:
            - label: "Voice Message (TTS)"
              value: "tts"
            - label: "Play Sound File"
              value: "sound"
    tts_message:
      name: Voice Message
      description: The sentence Alexa will speak.
      default: "There is someone at the door"
      selector:
        text:
    sound_file:
      name: Sound File Path
      description: "Example: 'amzn_sfx_doorbell_chime_01' or a local media URL."
      default: "amzn_sfx_doorbell_chime_01"
      selector:
        text:
    announcement_volume:
      name: Announcement Volume
      description: The volume level (0 to 1). Set to 0 to keep current volume.
      default: 0.5
      selector:
        number:
          min: 0
          max: 1
          step: 0.05
          mode: slider
    repeat_delay:
      name: Repeat Delay (Seconds)
      description: Set to 0 to play only once.
      default: 0
      selector:
        number:
          min: 0
          max: 30
          unit_of_measurement: s

# This section maps the inputs to variables so they work inside templates {{ }}
variables:
  v_volume: !input announcement_volume
  v_type: !input announcement_type
  v_repeat: !input repeat_delay
  v_devices: !input echo_devices
  v_message: !input tts_message
  v_sound: !input sound_file

mode: single

trigger:
  - platform: state
    entity_id: !input trigger_sensor
    from: "off"
    to: "on"

action:
  # 1. Set the volume if specified (greater than 0)
  - if:
      - condition: template
        value_template: "{{ v_volume | float > 0 }}"
    then:
      - service: media_player.volume_set
        target:
          entity_id: "{{ v_devices }}"
        data:
          volume_level: "{{ v_volume | float }}"

  # 2. Perform the announcement (First time)
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ v_type == 'tts' }}"
        sequence:
          - service: notify.alexa_media
            data:
              target: "{{ v_devices }}"
              message: "{{ v_message }}"
              data:
                type: tts
      - conditions:
          - condition: template
            value_template: "{{ v_type == 'sound' }}"
        sequence:
          - service: media_player.play_media
            target:
              entity_id: "{{ v_devices }}"
            data:
              media_content_id: "{{ v_sound }}"
              media_content_type: sound

  # 3. Handle the Repeat (If delay is greater than 0)
  - if:
      - condition: template
        value_template: "{{ v_repeat | int > 0 }}"
    then:
      - delay:
          seconds: "{{ v_repeat | int }}"
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ v_type == 'tts' }}"
            sequence:
              - service: notify.alexa_media
                data:
                  target: "{{ v_devices }}"
                  message: "{{ v_message }}"
                  data:
                    type: tts
          - conditions:
              - condition: template
                value_template: "{{ v_type == 'sound' }}"
            sequence:
              - service: media_player.play_media
                target:
                  entity_id: "{{ v_devices }}"
                data:
                  media_content_id: "{{ v_sound }}"
                  media_content_type: sound
