blueprint:
  name: "Alexa Doorbell Announcer (V1.3)"
  description: >
    Announce doorbell, door or any binary sensor events over Alexa. 
    Supports Alexa Sound Library or custom Voice Messages.
    
    Browse the full sound library here: https://developer.amazon.com/en-US/docs/alexa/custom-skills/ask-soundlibrary-reference.html
  domain: automation
  input:
    trigger_sensor:
      name: Doorbell or Door Sensor
      description: The sensor that triggers the announcement (Doorbell or Contact).
      selector:
        entity:
          domain: binary_sensor
    echo_devices:
      name: Alexa Devices
      description: Select one or more Echo devices.
      selector:
        entity:
          domain: media_player
          multiple: true
    announcement_type:
      name: Announcement Type
      description: Choose if Alexa should speak text or play a library sound.
      default: "tts"
      selector:
        select:
          options:
            - label: "Voice Message (TTS)"
              value: "tts"
            - label: "Amazon Library Sound"
              value: "sound"
    tts_message:
      name: Voice Message
      description: What Alexa will say (if Voice Message is selected).
      default: "There is someone at the door"
      selector:
        text:
    sound_preset:
      name: Popular Sound Presets
      description: "Choose a common sound, or select 'Custom' to use the URI box below."
      default: "soundbank://soundlibrary/home/amzn_sfx_doorbell_chime_01"
      selector:
        select:
          options:
            - label: "Standard Doorbell 1"
              value: "soundbank://soundlibrary/home/amzn_sfx_doorbell_chime_01"
            - label: "Classic Doorbell 2"
              value: "soundbank://soundlibrary/home/amzn_sfx_doorbell_chime_02"
            - label: "Electronic Chime"
              value: "soundbank://soundlibrary/home/amzn_sfx_doorbell_chime_03"
            - label: "Church Bell"
              value: "soundbank://soundlibrary/home/amzn_sfx_church_bell_1x_01"
            - label: "Sci-Fi Chime"
              value: "soundbank://soundlibrary/scifi/amzn_sfx_scifi_doorbell_01"
            - label: "--- USE CUSTOM URI BELOW ---"
              value: "custom"
    sound_uri:
      name: Custom Amazon Sound URI
      description: >
        Only used if 'Custom' is selected above. 
        Get URIs here: https://developer.amazon.com/en-US/docs/alexa/custom-skills/ask-soundlibrary-reference.html
      default: "soundbank://soundlibrary/animals/amzn_sfx_bear_groan_roar_01"
      selector:
        text:
    announcement_volume:
      name: Announcement Volume
      description: 0 to 1. Set to 0 to not change volume.
      default: 0.5
      selector:
        number:
          min: 0
          max: 1
          step: 0.05
          mode: slider
    repeat_delay:
      name: Repeat Delay (Seconds)
      description: Set to 0 to play only once.
      default: 0
      selector:
        number:
          min: 0
          max: 30
          unit_of_measurement: s

variables:
  v_devices: !input echo_devices
  v_type: !input announcement_type
  v_message: !input tts_message
  v_preset: !input sound_preset
  v_uri: !input sound_uri
  v_volume: !input announcement_volume
  v_repeat: !input repeat_delay

mode: single

trigger:
  - platform: state
    entity_id: !input trigger_sensor
    from: "off"
    to: "on"

action:
  # 1. Set Volume
  - if:
      - condition: template
        value_template: "{{ v_volume | float > 0 }}"
    then:
      - service: media_player.volume_set
        target:
          entity_id: "{{ v_devices }}"
        data:
          volume_level: "{{ v_volume | float }}"

  # 2. Play Announcement (First time)
  - service: notify.alexa_media
    data:
      target: "{{ v_devices }}"
      data:
        type: tts
      message: >
        {% if v_type == 'tts' %}
          {{ v_message }}
        {% else %}
          {% if v_preset == 'custom' %}
            <audio src='{{ v_uri }}'/>
          {% else %}
            <audio src='{{ v_preset }}'/>
          {% endif %}
        {% endif %}

  # 3. Handle Repeat
  - if:
      - condition: template
        value_template: "{{ v_repeat | int > 0 }}"
    then:
      - delay:
          seconds: "{{ v_repeat | int }}"
      - service: notify.alexa_media
        data:
          target: "{{ v_devices }}"
          data:
            type: tts
          message: >
            {% if v_type == 'tts' %}
              {{ v_message }}
            {% else %}
              {% if v_preset == 'custom' %}
                <audio src='{{ v_uri }}'/>
              {% else %}
                <audio src='{{ v_preset }}'/>
              {% endif %}
            {% endif %}
