blueprint:
  name: AI Event Summary - thefunkygibbon edit (v1.6.3 - Memory & Safe Clean)
  author: valentinfrlch (Refined by thefunkygibbon)
  homeassistant:
    min_version: 2024.10.0
  description: 'AI-powered summaries. RESTORED: v1.6.0 logic + Memory + Safe Unique Paths + Optional Cleanup.'
  domain: automation
  input:
    # --- TRIGGER SETTINGS ---
    camera_entities:
      name: Camera Entities
      default: []
      selector:
        entity:
          multiple: true
          filter:
            - domain: [camera]
    trigger_state:
      name: Trigger State
      default: recording
      selector:
        text: {}
    motion_sensors:
      name: Motion Sensor
      default: []
      selector:
        entity:
          multiple: true
          filter:
            - domain: [binary_sensor]
    
    # --- AI SETTINGS ---
    provider:
      name: Provider
      selector:
        config_entry:
          integration: llmvision
    model:
      name: Model
      selector:
        text: {}
    message:
      name: Prompt
      default: 'Summarize the events based on a series of images captured at short intervals. Focus only on moving subjects. Provide a clear and concise account.'
      selector:
        text:
          multiline: true
    use_memory:
      name: Use Memory
      description: "Enable if your AI provider supports memory/conversation history."
      default: false
      selector:
        boolean: {}
    duration:
      name: Duration
      default: 5
      selector:
        number:
          min: 1
          max: 60
          step: 1
          mode: slider
    max_frames:
      name: Max Frames
      default: 3
      selector:
        number:
          min: 1
          max: 60
          step: 1
          mode: slider
    store_in_timeline:
      name: Store in Timeline
      default: true
      selector:
        boolean: {}

    # --- NOTIFICATION SETTINGS ---
    notify_device:
      name: Notify Device
      default: []
      selector:
        device:
          multiple: true
          filter:
            - integration: mobile_app
    
    # --- CLEANUP SETTINGS ---
    auto_cleanup:
      name: Enable Auto-Cleanup
      description: "Delete the snapshot from /config/www/snapshots after the delay below."
      default: false
      selector:
        boolean: {}
    cleanup_delay:
      name: Cleanup Delay (Minutes)
      default: 10
      selector:
        number:
          min: 1
          max: 1440
          unit_of_measurement: min
          mode: box

variables:
  # Base Inputs
  camera_entities_list: !input camera_entities
  motion_sensors_list: !input motion_sensors
  notify_devices: !input notify_device
  auto_cleanup: !input auto_cleanup
  cleanup_delay: !input cleanup_delay
  use_memory: !input use_memory
  
  # Camera Logic (The v1.6.0 Version)
  camera_entity: >-
    {% if trigger is defined and motion_sensors_list and trigger.entity_id in motion_sensors_list %}
      {% set idx = motion_sensors_list.index(trigger.entity_id) %}
      {{ camera_entities_list[idx] if idx < camera_entities_list|length else camera_entities_list[0] }}
    {% elif trigger is defined and trigger.entity_id in camera_entities_list %}
      {{ trigger.entity_id }}
    {% else %}
      {{ camera_entities_list[0] }}
    {% endif %}

  camera_name_clean: "{{ camera_entity.replace('camera.', '').replace('.', '_') }}"
  
  # SAFE UNIQUE PATHING
  unique_id: "{{ as_timestamp(now()) | int }}"
  snapshot_file: "/config/www/snapshots/{{ camera_name_clean }}_{{ unique_id }}.jpg"
  snapshot_url: "/local/snapshots/{{ camera_name_clean }}_{{ unique_id }}.jpg"
  
  notification_tag: "llm_event_{{ camera_name_clean }}"
  
  # Device Entity Mapper (v1.6.0 Logic)
  device_entities: >-
    {% set ns = namespace(devices=[]) %}
    {% for dev in notify_devices %}
      {% set name = device_attr(dev, 'name') %}
      {% set slug = name | slugify %}
      {% set ns.devices = ns.devices + ['mobile_app_' + slug] %}
    {% endfor %}
    {{ ns.devices }}

max_exceeded: silent
mode: parallel
max: 10

trigger:
- platform: state
  entity_id: !input camera_entities
  to: !input trigger_state
- platform: state
  entity_id: !input motion_sensors
  to: 'on'

action:
  # 1. Take Snapshot
  - action: camera.snapshot
    target:
      entity_id: "{{ camera_entity }}"
    data:
      filename: "{{ snapshot_file }}"

  # 2. Initial Notification
  - repeat:
      for_each: "{{ device_entities }}"
      sequence:
        - action: "notify.{{ repeat.item }}"
          data:
            title: "Motion: {{ camera_name_clean | capitalize }}"
            message: "Analyzing..."
            data:
              tag: "{{ notification_tag }}"
              image: "{{ snapshot_url }}"
              attachment:
                url: "{{ snapshot_url }}"
                content-type: jpeg
                hide-thumbnail: false
              clickAction: "{{ snapshot_url }}"
              url: "{{ snapshot_url }}"

  # 3. Stream Analyzer (Memory Restored)
  - alias: Analyze event
    action: llmvision.stream_analyzer
    data:
      image_entity: ["{{ camera_entity }}"]
      provider: !input provider
      model: !input model
      message: !input message
      use_memory: "{{ use_memory }}" # Memory parameter restored here
      duration: !input duration
      max_frames: !input max_frames
      store_in_timeline: !input store_in_timeline
      generate_title: !input store_in_timeline
      expose_images: true
    response_variable: response

  # 4. Final Notification
  - repeat:
      for_each: "{{ device_entities }}"
      sequence:
        - action: "notify.{{ repeat.item }}"
          data:
            title: "{{ response.title if response.title else 'AI Analysis' }}"
            message: "{{ response.response_text }}"
            data:
              tag: "{{ notification_tag }}"
              image: "{{ snapshot_url }}"
              attachment:
                url: "{{ snapshot_url }}"
                content-type: jpeg
                hide-thumbnail: false
              clickAction: "{{ snapshot_url }}"
              url: "{{ snapshot_url }}"
              actions:
                - action: "URI"
                  title: "View Snapshot"
                  uri: "{{ snapshot_url }}"

  # 5. Optional Cleanup
  - if:
      - condition: template
        value_template: "{{ auto_cleanup }}"
    then:
      - delay:
          minutes: "{{ cleanup_delay }}"
      - continue_on_error: true
        action: shell_command.remove_llm_temp_file
        data:
          file: "{{ snapshot_file }}"
