blueprint:
  name: AI Event Summary (v1.9.0 - Flexible Presence & UI)
  author: valentinfrlch (Refined by Gemini)
  homeassistant:
    min_version: 2024.10.0
  description: 'AI-powered summaries. Enhanced with Cooldown, Memory, Auto-Cleanup, granular Schedules, independent Presence Detection, and Collapsible UI Sections.'
  domain: automation
  
  input:
    # ==========================================
    # 1. TRIGGERS & SENSORS
    # ==========================================
    section_trigger:
      name: ðŸŽ¯ Triggers & Sensors
      description: "Select the cameras and motion sensors that trigger this automation."
      icon: mdi:cctv
      input:
        camera_entities:
          name: Camera Entities
          default: []
          selector:
            entity:
              multiple: true
              filter:
                - domain: [camera]
        trigger_state:
          name: Trigger State
          default: recording
          selector:
            text: {}
        motion_sensors:
          name: Motion Sensor
          default: []
          selector:
            entity:
              multiple: true
              filter:
                - domain: [binary_sensor]

    # ==========================================
    # 2. GLOBAL CONDITIONS
    # ==========================================
    section_global:
      name: â±ï¸ Global Conditions
      description: "Settings that act as gatekeepers for the ENTIRE automation."
      icon: mdi:gate
      input:
        cooldown:
          name: Cooldown
          description: "Minimum time to wait before the automation can trigger again."
          default:
            minutes: 2
          selector:
            duration: {}
        global_presence_sensor:
          name: Global Presence Sensor (Optional)
          description: "Stop the ENTIRE automation from running unless this entity is in the target state."
          default: []
          selector:
            entity:
              multiple: false
        global_presence_state:
          name: Global Target State
          description: "The state the sensor above must be in (e.g., 'not_home')."
          default: "not_home"
          selector:
            text: {}

    # ==========================================
    # 3. AI ANALYSIS CONFIGURATION
    # ==========================================
    section_ai:
      name: ðŸ§  AI Analysis Settings
      description: "Configure the LLM and specific schedules/presence for when AI should run."
      icon: mdi:brain
      input:
        provider:
          name: Provider
          selector:
            config_entry:
              integration: llmvision
        model:
          name: Model
          selector:
            text: {}
        message:
          name: Prompt
          default: 'Summarize the events based on a series of images captured at short intervals. Focus only on moving subjects. Provide a clear and concise account.'
          selector:
            text:
              multiline: true
        use_memory:
          name: Use Memory
          description: "Enable if your AI provider supports memory/conversation history."
          default: false
          selector:
            boolean: {}
        duration:
          name: Duration
          default: 5
          selector:
            number:
              min: 1
              max: 60
              step: 1
              mode: slider
        max_frames:
          name: Max Frames
          default: 3
          selector:
            number:
              min: 1
              max: 60
              step: 1
              mode: slider
        store_in_timeline:
          name: Store in Timeline
          default: true
          selector:
            boolean: {}
        
        # AI Specific Conditions
        ai_schedule_enabled:
          name: Enable AI Time Schedule
          default: false
          selector:
            boolean: {}
        ai_schedule_start:
          name: AI Allowed Start Time
          default: "00:00:00"
          selector:
            time: {}
        ai_schedule_end:
          name: AI Allowed End Time
          default: "23:59:59"
          selector:
            time: {}
        ai_presence_sensor:
          name: AI Presence Sensor (Optional)
          description: "Only run AI when this entity matches the target state. (If blank, AI ignores presence)."
          default: []
          selector:
            entity:
              multiple: false
        ai_presence_state:
          name: AI Target State
          description: "The state the AI sensor above must be in (e.g., 'not_home')."
          default: "not_home"
          selector:
            text: {}

    # ==========================================
    # 4. NOTIFICATIONS & IMAGES
    # ==========================================
    section_image:
      name: ðŸ–¼ï¸ Notifications & Images
      description: "Configure your devices and the conditions for attaching images."
      icon: mdi:image
      input:
        notify_device:
          name: Notify Device
          default: []
          selector:
            device:
              multiple: true
              filter:
                - integration: mobile_app
        
        # Image Specific Conditions
        image_schedule_enabled:
          name: Enable Image Time Schedule
          default: false
          selector:
            boolean: {}
        image_schedule_start:
          name: Image Allowed Start Time
          default: "00:00:00"
          selector:
            time: {}
        image_schedule_end:
          name: Image Allowed End Time
          default: "23:59:59"
          selector:
            time: {}
        image_presence_sensor:
          name: Image Presence Sensor (Optional)
          description: "Only attach images when this entity matches the target state. (If blank, always attach)."
          default: []
          selector:
            entity:
              multiple: false
        image_presence_state:
          name: Image Target State
          description: "The state the Image sensor above must be in (e.g., 'not_home')."
          default: "not_home"
          selector:
            text: {}

    # ==========================================
    # 5. CLEANUP SETTINGS
    # ==========================================
    section_cleanup:
      name: ðŸ§¹ File Auto-Cleanup
      description: "Automatically delete snapshot images from your system after a delay."
      icon: mdi:broom
      input:
        auto_cleanup:
          name: Enable Auto-Cleanup
          default: false
          selector:
            boolean: {}
        cleanup_delay:
          name: Cleanup Delay (Minutes)
          default: 10
          selector:
            number:
              min: 1
              max: 1440
              unit_of_measurement: min
              mode: box

variables:
  # Base Inputs
  camera_entities_list: !input camera_entities
  motion_sensors_list: !input motion_sensors
  notify_devices: !input notify_device
  auto_cleanup: !input auto_cleanup
  cleanup_delay: !input cleanup_delay
  use_memory: !input use_memory
  cooldown: !input cooldown
  
  # Presence Variables
  global_presence_sensor: !input global_presence_sensor
  global_presence_state: !input global_presence_state
  ai_presence_sensor: !input ai_presence_sensor
  ai_presence_state: !input ai_presence_state
  image_presence_sensor: !input image_presence_sensor
  image_presence_state: !input image_presence_state
  
  # Schedule Variables
  ai_schedule_enabled: !input ai_schedule_enabled
  ai_schedule_start: !input ai_schedule_start
  ai_schedule_end: !input ai_schedule_end
  image_schedule_enabled: !input image_schedule_enabled
  image_schedule_start: !input image_schedule_start
  image_schedule_end: !input image_schedule_end

  # --- DYNAMIC EVALUATION LOGIC ---
  # AI Execution Gate
  run_ai: >-
    {% set schedule_ok = true %}
    {% if ai_schedule_enabled %}
      {% set now_time = now() %}
      {% set start_time = today_at(ai_schedule_start) %}
      {% set end_time = today_at(ai_schedule_end) %}
      {% if start_time < end_time %}
        {% set schedule_ok = start_time <= now_time <= end_time %}
      {% else %}
        {% set schedule_ok = now_time >= start_time or now_time <= end_time %}
      {% endif %}
    {% endif %}
    {% set presence_ok = true %}
    {% if ai_presence_sensor %}
      {% set presence_ok = states(ai_presence_sensor) == ai_presence_state %}
    {% endif %}
    {{ schedule_ok and presence_ok }}

  # Image Attachment Gate
  send_image: >-
    {% set schedule_ok = true %}
    {% if image_schedule_enabled %}
      {% set now_time = now() %}
      {% set start_time = today_at(image_schedule_start) %}
      {% set end_time = today_at(image_schedule_end) %}
      {% if start_time < end_time %}
        {% set schedule_ok = start_time <= now_time <= end_time %}
      {% else %}
        {% set schedule_ok = now_time >= start_time or now_time <= end_time %}
      {% endif %}
    {% endif %}
    {% set presence_ok = true %}
    {% if image_presence_sensor %}
      {% set presence_ok = states(image_presence_sensor) == image_presence_state %}
    {% endif %}
    {{ schedule_ok and presence_ok }}

  # Camera Logic
  camera_entity: >-
    {% if trigger is defined and motion_sensors_list and trigger.entity_id in motion_sensors_list %}
      {% set idx = motion_sensors_list.index(trigger.entity_id) %}
      {{ camera_entities_list[idx] if idx < camera_entities_list|length else camera_entities_list[0] }}
    {% elif trigger is defined and trigger.entity_id in camera_entities_list %}
      {{ trigger.entity_id }}
    {% else %}
      {{ camera_entities_list[0] }}
    {% endif %}

  camera_name_clean: "{{ camera_entity.replace('camera.', '').replace('.', '_') }}"
  
  # SAFE UNIQUE PATHING
  unique_id: "{{ as_timestamp(now()) | int }}"
  snapshot_file: "/config/www/snapshots/{{ camera_name_clean }}_{{ unique_id }}.jpg"
  snapshot_url: "/local/snapshots/{{ camera_name_clean }}_{{ unique_id }}.jpg"
  
  notification_tag: "llm_event_{{ camera_name_clean }}"
  
  # Device Entity Mapper
  device_entities: >-
    {% set ns = namespace(devices=[]) %}
    {% for dev in notify_devices %}
      {% set name = device_attr(dev, 'name') %}
      {% set slug = name | slugify %}
      {% set ns.devices = ns.devices + ['mobile_app_' + slug] %}
    {% endfor %}
    {{ ns.devices }}

max_exceeded: silent
mode: parallel
max: 10

trigger:
- platform: state
  entity_id: !input camera_entities
  to: !input trigger_state
- platform: state
  entity_id: !input motion_sensors
  to: 'on'

# --- THE GLOBAL CONDITION BLOCK ---
# If these fail, the automation stops entirely and does nothing.
condition:
  # 1. Cooldown Check
  - condition: template
    value_template: >-
      {% set dt = state_attr(this.entity_id, 'last_triggered') %}
      {% if dt %}
        {% set d = cooldown %}
        {% set total_seconds = (d.days | default(0) * 86400) + (d.hours | default(0) * 3600) + (d.minutes | default(0) * 60) + (d.seconds | default(0)) %}
        {{ (now() - dt).total_seconds() >= total_seconds }}
      {% else %}
        true
      {% endif %}
  # 2. Global Presence Check (Only blocks if sensor is assigned)
  - condition: template
    value_template: >-
      {% if global_presence_sensor %}
        {{ states(global_presence_sensor) == global_presence_state }}
      {% else %}
        true
      {% endif %}

action:
  # 1. Take Snapshot
  - if:
      - condition: template
        value_template: "{{ run_ai or send_image }}"
    then:
      - action: camera.snapshot
        target:
          entity_id: "{{ camera_entity }}"
        data:
          filename: "{{ snapshot_file }}"

  # 2. Main Logic Split
  - if:
      - condition: template
        value_template: "{{ run_ai }}"
    then:
      # ==================================
      # PATH A: AI IS ENABLED
      # ==================================
      - repeat:
          for_each: "{{ device_entities }}"
          sequence:
            - if:
                - condition: template
                  value_template: "{{ send_image }}"
              then:
                - action: "notify.{{ repeat.item }}"
                  data:
                    title: "Motion: {{ camera_name_clean | capitalize }}"
                    message: "Analyzing..."
                    data:
                      tag: "{{ notification_tag }}"
                      image: "{{ snapshot_url }}"
                      attachment:
                        url: "{{ snapshot_url }}"
                        content-type: jpeg
                        hide-thumbnail: false
                      clickAction: "{{ snapshot_url }}"
                      url: "{{ snapshot_url }}"
              else:
                - action: "notify.{{ repeat.item }}"
                  data:
                    title: "Motion: {{ camera_name_clean | capitalize }}"
                    message: "Analyzing..."
                    data:
                      tag: "{{ notification_tag }}"

      - alias: Analyze event
        action: llmvision.stream_analyzer
        data:
          image_entity: ["{{ camera_entity }}"]
          provider: !input provider
          model: !input model
          message: !input message
          use_memory: "{{ use_memory }}"
          duration: !input duration
          max_frames: !input max_frames
          store_in_timeline: !input store_in_timeline
          generate_title: !input store_in_timeline
          expose_images: true
        response_variable: response

      - repeat:
          for_each: "{{ device_entities }}"
          sequence:
            - if:
                - condition: template
                  value_template: "{{ send_image }}"
              then:
                - action: "notify.{{ repeat.item }}"
                  data:
                    title: "{{ response.title if response.title else 'AI Analysis' }}"
                    message: "{{ response.response_text }}"
                    data:
                      tag: "{{ notification_tag }}"
                      image: "{{ snapshot_url }}"
                      attachment:
                        url: "{{ snapshot_url }}"
                        content-type: jpeg
                        hide-thumbnail: false
                      clickAction: "{{ snapshot_url }}"
                      url: "{{ snapshot_url }}"
                      actions:
                        - action: "URI"
                          title: "View Snapshot"
                          uri: "{{ snapshot_url }}"
              else:
                - action: "notify.{{ repeat.item }}"
                  data:
                    title: "{{ response.title if response.title else 'AI Analysis' }}"
                    message: "{{ response.response_text }}"
                    data:
                      tag: "{{ notification_tag }}"
    else:
      # ==================================
      # PATH B: AI IS DISABLED
      # ==================================
      - repeat:
          for_each: "{{ device_entities }}"
          sequence:
            - if:
                - condition: template
                  value_template: "{{ send_image }}"
              then:
                - action: "notify.{{ repeat.item }}"
                  data:
                    title: "Motion: {{ camera_name_clean | capitalize }}"
                    message: "Motion detected."
                    data:
                      tag: "{{ notification_tag }}"
                      image: "{{ snapshot_url }}"
                      attachment:
                        url: "{{ snapshot_url }}"
                        content-type: jpeg
                        hide-thumbnail: false
                      clickAction: "{{ snapshot_url }}"
                      url: "{{ snapshot_url }}"
              else:
                - action: "notify.{{ repeat.item }}"
                  data:
                    title: "Motion: {{ camera_name_clean | capitalize }}"
                    message: "Motion detected."
                    data:
                      tag: "{{ notification_tag }}"

  # 3. Optional Cleanup
  - if:
      - condition: template
        value_template: "{{ auto_cleanup and (run_ai or send_image) }}"
    then:
      - delay:
          minutes: "{{ cleanup_delay }}"
      - continue_on_error: true
        action: shell_command.remove_llm_temp_file
        data:
          file: "{{ snapshot_file }}"
