blueprint:
  name: Door controlled heater Summer
  description: Raise heater temp to 26 when opening window and bring back with delay
  domain: automation
  source_url: https://github.com/thefunkygibbon/homeassistant/edit/main/smartthermostat2.yaml
  input:
    heating_target:
      name: Heater
      selector:
        entity:
          domain: climate
    door_entity:
      name: Door Sensor
      selector:
        entity: {}
    door_closed_wait:
      name: Wait time open
      description: Time to leave the heating on after door is opened.
      default: 120
      selector:
        number:
          min: 0.0
          max: 3600.0
          unit_of_measurement: seconds
          mode: slider
          step: 1.0
    door_opened_wait:
      name: Wait time closed
      description: Time to leave the heating off after door is closed.
      default: 120
      selector:
        number:
          min: 0.0
          max: 3600.0
          unit_of_measurement: seconds
          mode: slider
          step: 1.0
    target_temp:
      name: Target Temperature
      description: Temperature to set the heater to.
      default: 20
      selector:
        number:
          min: 0.0
          max: 40
          unit_of_measurement: degrees
          mode: slider
          step: 0.1
    default_temp:
      name: Default Temperature
      description: Temperature to set the heater back down to when not in use
      default: 10
      selector:
        number:
          min: 0.0
          max: 40
          unit_of_measurement: degrees
          mode: slider
          step: 0.1 
mode: restart
max_exceeded: silent
variables:
  heating_target: !input 'heating_target'
  heating_temperature: '{{ state_attr(heating_target, ''temperature'') }}'
trigger:
  platform: state
  entity_id: !input 'door_entity'
  from: 'off'
  to: 'on'
action:
- delay: !input 'door_opened_wait'
- service: climate.set_temperature
  entity_id: !input 'heating_target'
  data:
    temperature: !input 'default_temp'
- wait_for_trigger:
    platform: state
    entity_id: !input 'door_entity'
    from: 'on'
    to: 'off'
- delay: !input 'door_closed_wait'
- service: climate.set_temperature
  entity_id: !input 'heating_target'
  data:
    temperature: !input 'target_temp'
- service: climate.set_temperature
  entity_id: !input 'heating_target'
  data:
    temperature: '{{heating_temperature}}'
